### PR TITLE
Remove legacy add-on ID for Crash Hero (crh)

### PR DESCRIPTION
**Pull request by josephsl**
Removes legacy add-on ID for Crash Hero.

### CODE REVIEW

**Comment by seanbudd** [comment]
Have you gotten permission from @derekriemer to do this?

**Comment by seanbudd** [comment]
Closing - feel free to reopen once the add-on author has confirmed they wish for it to be removed. Note that there is still value in hosting legacy add-ons - i.e. it allows users to download old versions for old versions of NVDA

**Comment by derekriemer** [comment]
Sorry forgot to reply here.
Yes, this legacy id can be removed.
Derek Riemer
Improving the world one byte at a time!        ⠠⠊⠍⠏⠗⠕⠧⠬ ⠮ ⠸⠺ ⠐⠕ ⠃⠽⠞⠑ ⠁⠞ ⠁
⠐⠞⠖

•    Personal website: https://derekriemer.com
•    Email: ***@***.***
•    Phone: (303) 906-2194

**Comment by josephsl** [comment]
In this case, let's proceed with the PR. Thanks for the info.

**Comment by derekriemer** [comment]
can't figure out how to reopen this. Sorry!

**Comment by josephsl** [comment]
I may need to recreate the PR from the same branch...

**Pull request closed without merging**
