### PR TITLE
Add non-legacy Speech History entry

### PR DESCRIPTION
**Pull request by jscholes**

### CODE REVIEW

**Comment by seanbudd** [comment]
re-triggering CI

**Comment by jscholes** [comment]
How should the add-on ID on the community add-ons site be updated?  The [migration guide](https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/migratingFromAddonFiles.md) doesn't explain.

**Comment by seanbudd** [comment]
@nvdaes - do you have any suggestions for a point of contact for authors who wish to update the addonId reference in the community add-ons website?

**Comment by XLTechie** [comment]
Ask someone to do it for you, or . . .

Follow translations process to get access to the assembla SVN for 
screenreaderTranslations, and edit the website/addons/addonName.mdwn file, to 
change the URL (usually at the end).

Happy to do it for you, if you indicate what it was and what it should be.

**Comment by jscholes** [comment]
@XLTechie It was sps, it is now speechHistory.  I didn't really follow who I should ask, nor the comments about the translation system, so would appreciate any assistance to make sure the new version is distributed via the community add-ons site and Add-On Updater.

**Comment by XLTechie** [comment]
> @XLTechie It was sps, it is now speechHistory. I didn't really follow who I should ask, nor the comments about the translation system, so would appreciate

Sorry, I was a bit brief about that, assuming knowledge.

In any case, the file=speechHistory endpoint is not yet live.

**Comment by seanbudd** [comment]
@jscholes - we do not maintain the community website, the community website suggests [the mailing list](https://nvda-addons.groups.io/g/nvda-addons) as a point of contact. I wanted to confirm with @nvdaes that this is appropriate before adding a link to the mailing list in our migration guide.

**Comment by nvdaes** [comment]
hi Sean, I can send an adminnotice on the addons mailing list, and also I have a small bot which sends notifications of updates to the views latest branch in the addon datastore repo; so I can send there a request and ask Chris Duffley if he can bost the toot on Mastodon. I created an account on Christopher server; so I"ll proceeded. I haven"t read this long thread. If someone needs my attention, please mention my username @nvdaes.Enviado desde mi iPhoneEl 27 mar 2023, a las 7:19, Sean Budd ***@***.***> escribió:﻿
@nvdaes - do you have any suggestions for a point of contact for authors who wish to update the addonId reference in the community add-ons website?

**Comment by nvdaes** [comment]
Please do it, this is appropriate, Sean.Enviado desde mi iPhoneEl 27 mar 2023, a las 8:09, Sean Budd ***@***.***> escribió:﻿
@jscholes - we do not maintain the community website, the community website suggests the mailing list as a point of contact. I wanted to confirm with @nvdaes that this is appropriate before adding a link to the mailing list in our migration guide.

**Comment by seanbudd** [comment]
Due to a GitHub limitation, PRs from an external fork cannot receive automated comments.

There are 2 validation errors with this submission:
- Submission 'homepage' must be set to 'https://github.com/jscholes/nvda-speech-history' in json file instead of None
- Submission filename and versionNumber mismatch error: versionNumberField: 2023.1.0 version from submission filename: 2023.1 expected submission filename: 2023.1.0.json

I suggest resubmitting via the issue form.

**Comment by jscholes** [comment]
> Submission 'homepage' must be set

This key was not set in the initial `.json` manifest for the legacy version of the add-on, and is listed as "optional" in the [metadata reference](https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/jsonMetadata.md):

* If it is in fact required, please update the documentation accordingly.
* If it isn't, this presumably doesn't need to be fixed, because the source URL is specified and they are one and the same.
* If the validation is failing because `manifest.ini` inside the add-on package references a homepage, I would suggest trying to fall back to any specified source URL in such scenarios to see if they match.

> Submission filename and versionNumber mismatch error

I don't know what this means.  Nowhere in the JSON manifest, nor in the URL/add-on filename, is "2023.1.0" referenced as the version number in full.  `0` is listed as `patch` under `"addonVersionNumber"`, as was the case for the legacy entry.  If this is the problematic part of the manifest, the validation results should say so, and the template probably shouldn't include `"patch"` set to `0`.

> I suggest resubmitting via the issue form.

Thank you for your time in exploring what was wrong.  I would have appreciated the opportunity to fix these validation errors on the existing PR, particularly given that I would have already done so if the automation was working.  This entire process, and the tone of the individuals involved from NVAccess and the community, has left quite a lot to be desired.  I'm also not convinced that re-submitting would resolve any of the important issues relating to the add-on's presence on the community site and in Add-On Updater, so I may just revisit add-on distribution once the kinks have been worked out.

**Comment by jscholes** [comment]
Also, just to point out that homepage isn't listed as a field, required or otherwise, on the [add-on submission new issue form](https://github.com/nvaccess/addon-datastore/blob/master/.github/ISSUE_TEMPLATE/registerAddon.yml).

**Comment by seanbudd** [comment]
>If it is in fact required, please update the documentation accordingly.
>If the validation is failing because manifest.ini inside the add-on package references a homepage, I would suggest trying to fall back to any specified source URL in such scenarios to see if they match.
>Also, just to point out that homepage isn't listed as a field, required or otherwise, on the [add-on submission new issue form](https://github.com/nvaccess/addon-datastore/blob/master/.github/ISSUE_TEMPLATE/registerAddon.yml).

As specified in the JSON metadata document, this must match the url field in the addon manifest. Both of these fields are optional.
I have opened a PR #357 which includes updating this message to be more clear.
Submitting a PR here should offer valid metadata, if you are explicitly submitting information don't expect the service "to fallback" and update your PR. The issue form exists explicitly for the purpose for add-on manifest information to be used to automatically generate matching submission data.

>I don't know what this means. Nowhere in the JSON manifest, nor in the URL/add-on filename, is "2023.1.0" referenced as the version number in full. 0 is listed as patch under "addonVersionNumber", as was the case for the legacy entry. If this is the problematic part of the manifest, the validation results should say so, and the template probably shouldn't include "patch" set to 0.

It appears that and old name for the field is beind used in that error message, I've opened a fix for that here: https://github.com/nvaccess/addon-datastore-validation/pull/22
It is expected that the file name and the addonVersionNumber have the patch number to be included.
This is stated in the submission guide, but I have updated the JSON metadata file to be more clear in #357.

**Comment by jscholes** [comment]
> if you are explicitly submitting information don't expect the service "to fallback" and update your PR.

I assume this is in relation to my comment:

> If the validation is failing because manifest.ini inside the add-on package references a homepage, I would suggest trying to fall back to any specified source URL in such scenarios to see if they match.

If so, my expectation was not that the system would make changes to my submission.  My suggestion was that the validation rules could be updated to check both the homepage and source URL fields, to see if one of them matched the URL in the add-on manifest.  After all, `manifest.ini` only accepts a single `url` key, with no distinction made between home/source.

**Comment by seanbudd** [comment]
The approach we took to create the schema was to assume that the "source url" field never existed, and the "url" field was historically used as a "homepage" field.
Note that the "url" field in the manifest spec in NVDA has this description: "URL for more information about the add-on. New versions and such."
As such, we expect the url field to match the homepage, and consider the source URL a separate and new metadata field

**Comment by XLTechie** [comment]
@jscholes wrote:

> This entire process, and the tone of the individuals involved from NVAccess and the community, has left quite a lot to be desired.

James, as one of those individuals from the community who offered to help you, 
and whose tone you mislike, here, I can only apologize again. I had assumed that 
you knew about the translation process, and editing files on the website, so 
only spoke about its details in summary. You have been around the add-on 
community far longer than I, and at a far deeper level. When I realized you 
weren't familiar with that process, I didn't explain further as you seemed happy 
to have the changes done for you, and I was happy to do them. I stood by the 
rest of the night to do that immediately upon the new version of the add-on 
being merged.

> I'm also not convinced that re-submitting would resolve any of the important issues relating to the add-on's presence on the community site and in Add-On Updater,

The URL in the manifest, maybe not. I tend to point to the readme of the add-on 
instead of the source homepage (though that is also often the readme).

However, the version problem might have been resolved if you submitted this (or 
do so in the future) via the issue form, as then you're letting the system 
generate the metadata for you. I could be wrong though.

> so I may just revisit add-on distribution once the kinks have been worked out.

Given how many of us are successfully submitting via the issue form and having 
rapid updates, most of the kinks have been. That aside, please reconsider your 
position. This is a very popular add-on, and I would ask you not to punish its 
users for technical issues relating to the submission process, or any offense 
we might have caused.
It's not a very mature process, perhaps, but it does work, and can be worked 
with with significant success.

**Comment by jscholes** [comment]
@XLTechie 

> I stood by the rest of the night to do that immediately upon the new version of the add-on being merged.

This is very much appreciated, and I'm sorry it didn't happen.

> This is a very popular add-on, and I would ask you not to punish its users for technical issues relating to the submission process, or any offense we might have caused.

I have manually reached out to the maintainer of Add-On Updater to get this add-on onto people's machines who want it.  That is something that the Add-On Store migration process doesn't currently seem equipped to handle, without insider knowledge and/or connections on the part of the contributor which I no longer possess.  I have not been playing an active role in the add-on community for quite some time now.

If you are still able to update the community site, the release is available on my GitHub and could presumably just be listed under the same ID.  I have closed the related PR to remove the legacy version, but I'm not sure if the lack of an update within the Store ecosystem is a blocker.

As for punishing users: I set aside some time to update the add-on following the release of NVDA 2023.1, and familiarise myself with the new Add-On Store submission process.  My submission was met with:

1. failed surfacing of automation check results that would have allowed me to resolve the validation errors;
2. no ready explanation of how to complete the migration on the community add-ons website assuming the validation issues could be addressed;
3. a manual explanation of the validation errors which themselves uncovered multiple issues within the validation system;
4. closure of the PR immediately after the provision of that explanation, rather than time to fix the issues that were raised; and
5. frankly, rude and abrasive responses to what I considered sound feedback suggestions, on a very new process for which NVAccess apparently are seeking feedback.

I take your points on board, and will consider resubmitting should I have the time to do so.  In the meantime, the negative tone has left me with a significant level of unease, and I don't feel it is reasonable to expect individual contributors to carry the burden of poor conduct purely to place the interests of end-users first.  Problems happen, on the part of both organisations and individual contributors.  How you respond to them matters, and I view this as an example of how not to do it.

Thank you, once again, for your time and offer of assistance.

**Pull request closed without merging**
