### PR TITLE
Remove enhancedAnnotationslegacy

### PR DESCRIPTION
**Pull request by nvdaes**

### CODE REVIEW

**Comment by seanbudd** [comment]
This removes several files that weren't uploaded from the legacy migration. Is there are reason why you wish to delete them?

**Comment by nvdaes** [comment]
Hi Sean:

Files aren't synchronized in the views branch and seems to needremoval
and resubmit, like I did with cursorLocator. See the legacy status of
enhancedAnnotations and thelatest version recognized in this webpage
created for testing:

https://nvdaes.github.io/nvdastore

2023-03-28 7:38 GMT+02:00, Sean Budd ***@***.***>:

**Comment by seanbudd** [comment]
Could you explain where you expect them to be in the views branch?
I am surprised they are not there, they should be.

**Comment by seanbudd** [comment]
It seems like there is a bug with the latest views generation

**Comment by seanbudd** [comment]
PR: https://github.com/nvaccess/addon-datastore-transform/pull/21

**Comment by nvdaes** [comment]
Thanks Sean. Now legacy is not shown, so this PR maybe just closed. I"ll do it in a few hours unless you have a different suggestion.

**Pull request closed without merging**
