### PR TITLE
Remove legacy Speech History entry

### PR DESCRIPTION
**Pull request by jscholes**

### CODE REVIEW

**Comment by seanbudd** [comment]
re-triggering CI

**Comment by seanbudd** [comment]
Apologies for the failing CI builds, something was recently pushed to master causing this.
When the community website links have been updated, let us know on this Pull Request so we can merge it.
It is probably not a good idea to merge this until the community website has been updated, otherwise their links will break.

**Comment by XLTechie** [comment]
@seanbudd but the PR with the replacement has not yet merged, so the 
community website links shouldn't be updated yet for the same reason.

**Comment by seanbudd** [comment]
It seems that the CI builds will not comment on PRs opened from external forks.

**Pull request closed without merging**
