### PR TITLE
Remove legacy add-on ID for Braile Extender (brlext)

### PR DESCRIPTION
**Pull request by josephsl**
Removes legacy add-on ID for Braille Extender (brlext).

### CODE REVIEW

**Comment by seanbudd** [comment]
Have you gotten permission from @aaclause to do this?
Note that legacy add-ons are still available in places (i.e. the legacy add-ons website and externally hosted views of the add-on store).

**Comment by kevinderome** [comment]
Hello,
is this a joke?
This module still has a large community and is maintained by its developer.

**Comment by josephsl** [comment]
Hi,

What I'm aiming at is removing duplicate add-on ID's - one legacy, one actual. This pull request does not deal with removing the add-on itself from the add-on store. I have asked add-ons community about it before, and have asked folks there again on this and other ad-dons with legacy ID's.

Thanks.

**Comment by seanbudd** [comment]
Closing - feel free to reopen once the add-on author has confirmed they wish for it to be removed. Note that there is still value in hosting legacy add-ons - i.e. it allows users to download old versions for old versions of NVDA

**Pull request closed without merging**
