### PR TITLE
[Submit add-on]: Newfon-2023.2.0

### PR DESCRIPTION
**Pull request by DraganRatkovich**

### CODE REVIEW

**Comment by DraganRatkovich** [comment]
@nvdaes Again this unknown problem, I no longer know what to do. Everything is correct in the metadata file.

**Comment by DraganRatkovich** [comment]
@nvdaes Here is the [link to the failed check](https://github.com/nvaccess/addon-datastore/actions/runs/4392919582/jobs/7692983588)

**Comment by nvdaes** [comment]
í"ll try to submit an issue to create a pr and check this.Enviado desde mi iPhoneEl 11 mar 2023, a las 16:17, DraganRatkovich ***@***.***> escribió:﻿
@nvdaes Again this unknown problem, I no longer know what to do. Everything is correct in the metadata file.

**Comment by DraganRatkovich** [comment]
@nvdaes Unfortunately, doesn't work either. I tried almost three times.

**Pull request closed without merging**
