### PR TITLE
Update thunderbirdPlus 4.6.3 checksum

### PR DESCRIPTION
**Pull request by seanbudd**
@CyrilleB79 it seems that the SHA has changed for this add-on version?

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Pierre-Louis (RPTools-org),  any idea why this checksum has changed? Maybe you have modified the release file in your GitHub repository?

If yes, beware that it is not expected that releases submitted to add-on store be modified. E.g. if you find an issue with the release 4.6.3, create a 4.6.4 and submit it rather than updating the 4.6.3.

**Comment by seanbudd** [comment]
@pierre-louis

**Comment by seanbudd** [comment]
Hi @CyrilleB79 - I'm not sure if Pierre would have got a notification for that message.

**Comment by RPTools-org** [comment]
Sorry, I'm not comfortable with the procedures yet. I thought it 
wouldn't change anything for you since the download link hasn't changed.

I didn't want to modify 5 readme.md files to add a new release link when 
the code has only undergone a small modification.

Regards

**Comment by seanbudd** [comment]
@RPTools-org - in future changing the file downloaded by the release link will make it unavailable to install through the add-on store. For security reasons we need to ensure that the file downloaded by the user is the same file submitted to the add-on store.

**Pull request merged**
