### PR TITLE
(Submit add-on): newfon-2023.2.0

### PR DESCRIPTION
**Pull request by DraganRatkovich**

### CODE REVIEW

**Comment by DraganRatkovich** [comment]
@nvdaes Unfortunately, still the same error. I changed the name of the add-on and removed the capital letters, but no change.

**Comment by nvdaes** [comment]
I see this error in GitHub Actions:

Unhandled error: Modifications to submitted add-ons will not be auto-approved

This add-on hasn't been sent previously, right? I mean with the same version.

**Comment by DraganRatkovich** [comment]
@nvdaes Before the add-on store was available, I submitted version 2023.1.0 the old way and now decided to change the version with minor changes such as changing the Newfon license and hence the version number 2023.2.0.

**Comment by nvdaes** [comment]
You may close all these pull request and I can try again. And we can report this if the addon cannot be added.Enviado desde mi iPhoneEl 11 mar 2023, a las 17:42, DraganRatkovich ***@***.***> escribió:﻿
@nvdaes Before the add-on store was available, I submitted version 2023.1.0 the old way and now decided to change the version with minor changes such as changing the Newfon license and hence the version number 2023.2.0.

**Comment by DraganRatkovich** [comment]
@nvdaes Okay, I'm closing this PR and you can try to add. Unfortunately, I can't close PRs that are open by GitHubActionsBot, so they will remain open, however, I have closed all issues related to this PR.

**Pull request closed without merging**
