### PR TITLE
Fix channels for add-ons wrongly declared as stable

### PR DESCRIPTION
**Pull request by nvdaes**
cc: @seanbudd @mesteranas @cyrmax @ahmedthebest31

### CODE REVIEW

**Comment by seanbudd** [comment]
@nvdaes - can you investigate why these actions succeeded and merged in the first place? 
This seems to be a regression as previously these actions would have failed.

https://github.com/nvaccess/addon-datastore/actions/runs/6765116360/job/18384361899

**Comment by seanbudd** [comment]
I'm concerned other validation errors may be slipping through

**Comment by nvdaes** [comment]
Í"ll investigate this, in particular if this happens when running all jobs and just failed jobs if a submitter is not registered; we may validate the metadata when the issue is labelled,not in the PR, if needed.

**Comment by nvdaes** [comment]
@seanbudd , this PR was needed due oto a regression: I reverted my commits and confirmed that then add-ons cannot be delcared stable with 2024.1.0 last tested version. I don't know what's the problem. I don't think this can be due to the usage of version 4 ofcheckout action.

**Pull request merged**
