### PR TITLE
Add cursorLocator 2023.02.17 add-on

### PR DESCRIPTION
**Pull request by nvdaes**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by nvdaes** [comment]
The workflow that I created time ago is working properly. Let's close this PR, creted just for testing.

**Comment by seanbudd** [comment]
Hi Noelia, 

I am merging this to enable auto-merge, as an example PR is required to enable auto-merge.
Let me know if it should be deleted.
After this is merged, auto-merge when checks pass is enabled on this repository.

**Comment by nvdaes** [comment]
seanbudd commented wrote:

> I am merging this to enable auto-merge, as an example PR is required to enable auto-merge.
Let me know if it should be deleted.

Hi Sean, don't delete this please. It's identical to version 3.0 sent to addonFiles repo, except that in 3.0 we mention that it's compatible with NVDA 2023.1 in the readme, but I think that this info maybe superfluous when the store is used, since it will present just the last version for compatible add-ons, so imo we dwon't need to specify this in the readme.
Thanks.
cc: @sergiogomez31

**Comment by nvdaes** [comment]
Just in case: I've tested various GitHub workflow files (GitHub Actions), to send add-ons to this repo in an easy way, for example, just pasting the download and source urls in a GitHub form. Now that pull requests can be merged automatically, I'll test a workflow with the [Enable pull request automerge action](https://github.com/peter-evans/enable-pull-request-automerge).
I'll do probably today with placeMarkers add-on, to complete my tests.

**Pull request merged**
