### PR TITLE
[Submit add-on]: Newfon-2023.2.0

### PR DESCRIPTION
**Pull request by DraganRatkovich**

### CODE REVIEW

**Comment by DraganRatkovich** [comment]
Hello,

@feerrenrut @seanbudd @josephsl I have been trying to merge for almost 2 days into master my add-on, however I am getting an error in the checks and please check the status of the checks and let me know what exactly is wrong with the PR. When I tried to open an issue to automatically generate the metadata json file, still got the same error, now I opened a PR with a new branch with my newly created json file and got the same error. Please check the generated status from GitHubActions and let me know what needs to be improved.

**Comment by DraganRatkovich** [comment]
I have tried almost everything with commits to fix PRMerge however it still fails. @feerrenrut @seanbudd @josephsl I look forward to your feedback and suggestions.

**Comment by DraganRatkovich** [comment]
Hi,

@nvdaes Maybe you can also give feedback on this, what is wrong with PR

**Comment by nvdaes** [comment]
Hello: Here appear two files changed but just one is accepted. If you deleted a file it counts also as changed.
I suggest you toclose this and send anew issue.

**Comment by DraganRatkovich** [comment]
@nvdaes Thanks for the reply, I'll give it a try now and see if PRMerge succeeds.

**Pull request closed without merging**
